package pa

import(
	"fmt"
	"github.com/emmansun/gmsm/smx509"
	"github.com/gotlcp/tlcp"
)

var (
	sigCertKey tlcp.Certificate
	encCertKey tlcp.Certificate
	rootCert   *smx509.Certificate
)

const (
//	ROOT_CERT_PEM = `-----BEGIN CERTIFICATE-----
//MIIB4zCCAYigAwIBAgIBATAKBggqgRzPVQGDdTBGMQswCQYDVQQGEwJBQTELMAkG
//A1UECAwCQkIxCzAJBgNVBAoMAkNDMQswCQYDVQQLDAJERDEQMA4GA1UEAwwHcm9v
//dCBjYTAgFw0yMzAyMjIwMjMwMTNaGA8yMTIzMDEyOTAyMzAxM1owRTELMAkGA1UE
//BhMCQUExCzAJBgNVBAgMAkJCMQswCQYDVQQKDAJDQzELMAkGA1UECwwCREQxDzAN
//BgNVBAMMBnN1YiBjYTBZMBMGByqGSM49AgEGCCqBHM9VAYItA0IABH0feWwae0S0
//w4QQA5cBGYwaQPaxZFcLzIqph+I6BQQCGXaIAabqpO0zjAyf1twYmoM3ZRLJgbZz
//HE/2rRMPBiajZjBkMB0GA1UdDgQWBBSsYesigGJZCD6WyNF/znRcAq88mTAfBgNV
//HSMEGDAWgBTG7uYyZVoHe+rslGLxQQUdzFUVjjASBgNVHRMBAf8ECDAGAQH/AgEA
//MA4GA1UdDwEB/wQEAwIBhjAKBggqgRzPVQGDdQNJADBGAiEApoHDue1bzGukE97O
//BqQbboU1d3jqNg4gAgpMe5fFIosCIQDwndSp7Tc3DZ0QCifXKNqgykjepsWTPZ3R
//NrMzM0rflg==
//-----END CERTIFICATE-----
//`
	ROOT_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIDYTCCAkkCFDRnhMvzCNtV1JuBmPQqxROgE+36MA0GCSqGSIb3DQEBCwUAMG0x
CzAJBgNVBAYTAkNOMQswCQYDVQQIDAJUSjELMAkGA1UEBwwCVEoxDDAKBgNVBAoM
A0lOUzEMMAoGA1UECwwDZGV2MQswCQYDVQQDDAJxcTEbMBkGCSqGSIb3DQEJARYM
eGthamZrZGpmbGRzMB4XDTIzMDkwODA5NDk1NloXDTI0MDkwNzA5NDk1NlowbTEL
MAkGA1UEBhMCQ04xCzAJBgNVBAgMAlRKMQswCQYDVQQHDAJUSjEMMAoGA1UECgwD
SU5TMQwwCgYDVQQLDANkZXYxCzAJBgNVBAMMAnFxMRswGQYJKoZIhvcNAQkBFgx4
a2FqZmtkamZsZHMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDUy7Mt
bHcul1BU+Luo9y6vouLkLEt+mIsEMuYU108UqxIfM+oqfwUnLIKpmht9HhcMyb6X
/uPwX4xiGqTvNMfFnS51jnD3UCfwHelsU0MpLIVC4Fy/c/fzY2ZCDGSobzUOM8fH
tsXTYLTGjh79px1pFhU2kmZ5ojEMkU4dj2iGxlWD8zLlX1oA/OWDtj4uC7dMnZ1g
gi3fvPVW/fk0OLl3nZdafRYsiSZLVXYIMFy8HmAYEGUrFgKOl//O91oE36oIkFsh
J8PC9IAts/rZsuv/Pxh0tpAEYl/GF/g4G3LxnTs7Xsa8Y9Xj5L5K/1eIUwdOaupV
kY7NkH1VMyMu+uFDAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAE/tIVh0VJ4SRQ64
zcyol8MTAech2m149rOGTb0VI6U6jvQjmDK9azoUfZ8KfEOOdvb3Mdt3D/OPcH/0
LH+os9g6iwpOCyvTUuXSlTObwBO0NiEVOQAnUeVko45qE3bkOTDLw73wHEVmoaMQ
epmEZbkMXdwaIvkU304xerZUbloJNJagk/nVYR9m+GWPVefzz+7+WgqFRTQVAqSN
dF1VgWqqotFmUkJTXhtaQzBvzECvcN/ER/HGZxTrnVV5xbTHu5TH1uMdL5qSLxPr
z8nTCreqVV46otluSo6Z7WEzXmIyj/3b3Pks7kNocyoKSvdDzM2dYNHioxmsP4ma
VRb1Ap4=
-----END CERTIFICATE-----`
	
	SIG_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIB7jCCAZOgAwIBAgIUcbKTlc6+CNoHglmEk+xm+WIqZcAwCgYIKoEcz1UBg3Uw
RTELMAkGA1UEBhMCQUExCzAJBgNVBAgMAkJCMQswCQYDVQQKDAJDQzELMAkGA1UE
CwwCREQxDzANBgNVBAMMBnN1YiBjYTAgFw0yMzAyMjIwMjMwMTRaGA8yMTIzMDEy
OTAyMzAxNFowSjELMAkGA1UEBhMCQUExCzAJBgNVBAgMAkJCMQswCQYDVQQKDAJD
QzELMAkGA1UECwwCREQxFDASBgNVBAMMC3NlcnZlciBzaWduMFkwEwYHKoZIzj0C
AQYIKoEcz1UBgi0DQgAEBb/67sQGyPP1gKbjnFKEdsDfK2EGXUp09HavD7ZokPiW
rMSyHYsDbRPxe9TTgjSQi+23f44+rocGVPxvqASNDKNaMFgwCQYDVR0TBAIwADAL
BgNVHQ8EBAMCBsAwHQYDVR0OBBYEFH3uBqkdowIvk//P7n5UtnpV9TR6MB8GA1Ud
IwQYMBaAFKxh6yKAYlkIPpbI0X/OdFwCrzyZMAoGCCqBHM9VAYN1A0kAMEYCIQCz
W/6Z/d/IJUTrO0o8nCxNle6R0AkRCKUFhW9zbIRlNwIhAJZxg4gs2cV2QF37oHs6
9TD+MkRbql4Yb47+jLf8f247
-----END CERTIFICATE-----
`
	ENC_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIB6zCCAZKgAwIBAgIUaNiS6WOsoEViDnmdb8Mdk3Qz5XwwCgYIKoEcz1UBg3Uw
RTELMAkGA1UEBhMCQUExCzAJBgNVBAgMAkJCMQswCQYDVQQKDAJDQzELMAkGA1UE
CwwCREQxDzANBgNVBAMMBnN1YiBjYTAgFw0yMzAyMjIwMjMwMTRaGA8yMTIzMDEy
OTAyMzAxNFowSTELMAkGA1UEBhMCQUExCzAJBgNVBAgMAkJCMQswCQYDVQQKDAJD
QzELMAkGA1UECwwCREQxEzARBgNVBAMMCnNlcnZlciBlbmMwWTATBgcqhkjOPQIB
BggqgRzPVQGCLQNCAAR9vqVFQ0WBcr07aI5QnC31RYas4AtY7JQUmflKUKWMZ11v
mtr/CJ6BN6djQ6zS81yjCopcz4G3zc5SZqAWueNko1owWDAJBgNVHRMEAjAAMAsG
A1UdDwQEAwIDODAdBgNVHQ4EFgQUZ6Wt1ZR24FqcXla4hg/xOyju7FQwHwYDVR0j
BBgwFoAUrGHrIoBiWQg+lsjRf850XAKvPJkwCgYIKoEcz1UBg3UDRwAwRAIgR1k1
ecSt7I2335jEquFmHBE5pe8Sk/IqOqQS0Jvs1uYCIG5XMB0XeUaVb9OctaxgOQLN
F8dRftiUHsyYXqfbaVjI
-----END CERTIFICATE-----
`
	SIG_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBG0wawIBAQQgeQTrKtO8mNXn/yvg
R+pdbCgH5sl+WCFfXcqGl64soU2hRANCAAQFv/ruxAbI8/WApuOcUoR2wN8rYQZd
SnT0dq8PtmiQ+JasxLIdiwNtE/F71NOCNJCL7bd/jj6uhwZU/G+oBI0M
-----END PRIVATE KEY-----
`
	ENC_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBG0wawIBAQQgLrRk3CWTe+WZOFSf
TMYwbOocLs3MSRpOO0/AvSmvH5mhRANCAAR9vqVFQ0WBcr07aI5QnC31RYas4AtY
7JQUmflKUKWMZ11vmtr/CJ6BN6djQ6zS81yjCopcz4G3zc5SZqAWueNk
-----END PRIVATE KEY-----
`
)
//sigCertKey tlcp.Certificate, encCertKey tlcp.Certificate, rootCert *smx509.Certificate
func LoadCert() (tlcp.Certificate, tlcp.Certificate, *smx509.Certificate) {
	var err error
	rootCert, err = smx509.ParseCertificatePEM([]byte(ROOT_CERT_PEM))
	if err != nil {
		fmt.Println(err.Error())
		panic(err)
	}
	sigCertKey, err = tlcp.X509KeyPair([]byte(SIG_CERT_PEM), []byte(SIG_KEY_PEM))
	if err != nil {
		fmt.Println(err.Error())
		panic(err)
	}
	encCertKey, err = tlcp.X509KeyPair([]byte(ENC_CERT_PEM), []byte(ENC_KEY_PEM))
	if err != nil {
		fmt.Println(err.Error())
		panic(err)
	}
	return sigCertKey, encCertKey, rootCert
}
